# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Film blog
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  This is my great blog where I talk about all things film, english, and random bits
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ""

# Chirpy theme settings
img_cdn: ""
# avatar: /assets/img/avatar-placeholder.jpg
lang: en
timezone: UTC

# Social settings
social: []
# Add social links if desired. 
# social:
#   - {icon: 'fab fa-github', link: 'https://github.com/yourhandle'}

# Build settings
theme: jekyll-theme-chirpy
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2

# Pagination
pagination:
  enabled: true
  per_page: 10
  permalink: /blog/page:num/
  title: ':title'
  trail:
    before: 1
    after: 1
  sort_field: 'date'
  sort_reverse: true

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/
  - _drafts/
  - README.md
  - LICENSE
  - feed.xml
